# Generated by Django 5.1.4 on 2025-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='bank_code',
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='bank_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
