# Generated by Django 5.1.4 on 2025-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_accountdetails_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='created_at',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='account_holder_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
