# Generated by Django 5.1.4 on 2025-01-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accountdetails_account_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetails',
        ),
    ]
